defaults: &defaults
  arrow_pass_host: 'http://arrow-pass.dev'
  client:
    app_key: 'DemoBoxOffice'
    app_secret: 'secret'
    
development:
  <<: *defaults

staging:
  <<: *defaults

production:
  <<: *defaults
  arrow_pass_host: 'http://qa.arrowpass.com'
